### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np


In [3]:
# numpy vector
vector = np.random.rand(10)
vector, vector.shape

(array([0.48574468, 0.78545162, 0.23176114, 0.73366056, 0.00288774,
        0.43271885, 0.97713169, 0.93056213, 0.9658175 , 0.92444023]),
 (10,))

In [9]:
# matrix
matrix = np.array([11, 14, 17, 20, 23, 26, 29, 32, 35]).reshape(3, 3)
matrix2 = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])
print("variant 1:", matrix)
print("variant 2:", matrix2)

variant 1: [[11 14 17]
 [20 23 26]
 [29 32 35]]
variant 2: [[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [12]:
# vector + 10
new_vector = np.round(vector + 10, 2)
new_vector

array([10.49, 10.79, 10.23, 10.73, 10.  , 10.43, 10.98, 10.93, 10.97,
       10.92])

In [14]:
# matrix x 2
matr_multip = matrix2 * 2
print(matr_multip)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [16]:
# vector **2
vector_squared = vector ** 2
print(vector_squared)

[2.35947894e-01 6.16934252e-01 5.37132259e-02 5.38257811e-01
 8.33901710e-06 1.87245601e-01 9.54786344e-01 8.65945877e-01
 9.32803439e-01 8.54589738e-01]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [17]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [20]:
# A x B
result_matrix = np.dot(A, B)
print("Result:", result_matrix)

Result: [[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]


In [28]:
# matrix x vector С
# matrix_vector = np.dot(result_matrix, C)
print("Після множення матриць А, В,  отримано розмірність 3х3. А вказаний вектор 2х1, тому виникає помилка.")

Після множення матриць А, В,  отримано розмірність 3х3. А вказаний вектор 2х1, тому виникає помилка.


In [29]:
# result_matrix x  matrix D
# matrixx = np.dot(result_matrix, D)
print("При множенні матриць різної форми (розмірності) виникає помилка, обчислення виконати не можна.")

При множенні матриць різної форми (розмірності) виникає помилка, обчислення виконати не можна.



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [31]:
# matrix transpose
result_matrix_t = result_matrix.T
print(result_matrix_t)


[[0.232  0.3061 0.1393]
 [0.1627 0.4867 0.2261]
 [0.2145 0.633  0.294 ]]


In [34]:
# vector transpose
vector_t = vector.T
print(vector)
print("---------------------------------------------------------------")
print(vector_t)

[0.48574468 0.78545162 0.23176114 0.73366056 0.00288774 0.43271885
 0.97713169 0.93056213 0.9658175  0.92444023]
---------------------------------------------------------------
[0.48574468 0.78545162 0.23176114 0.73366056 0.00288774 0.43271885
 0.97713169 0.93056213 0.9658175  0.92444023]


Зміни немає, тому що vector представлено одновимірним масивом.

In [35]:
# column vector
column_vector = np.expand_dims(vector, axis=1)
print(column_vector, column_vector.shape)


[[0.48574468]
 [0.78545162]
 [0.23176114]
 [0.73366056]
 [0.00288774]
 [0.43271885]
 [0.97713169]
 [0.93056213]
 [0.9658175 ]
 [0.92444023]] (10, 1)


Дана операція трансформувала одновимірний вектор у двовимірний вектор.

In [37]:
# column_vector transpose
column_vector_t = column_vector.T
print(column_vector_t, column_vector_t.shape)

[[0.48574468 0.78545162 0.23176114 0.73366056 0.00288774 0.43271885
  0.97713169 0.93056213 0.9658175  0.92444023]] (1, 10)
