1. Створення масивів
Масив зі списку [5, 15, 25, 35, 45]
Масив з нулів розміром 7
Масив з одиниць розміром 6
Масив з числами від 10 до 19 використовуючи np.arange()

In [3]:
import numpy as np
# масив зі списку
arr = np.array([5, 15, 25, 35, 45])
print(arr)

[ 5 15 25 35 45]


In [5]:
#масив з нулів
zeros = np.zeros((7))
print(zeros)

#масив з одиниць
ones = np.ones((6))
print(ones)

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [7]:
# масив з числами від 10-19
arr2 = np.arange(10, 20)
print(arr2)

[10 11 12 13 14 15 16 17 18 19]


2. Базові операції

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].
Помножте всі елементи на 2
Додайте до всіх елементів 10
Піднесіть всі елементи до квадрату
Обчисліть квадратний корінь з усіх елементів
Виведіть результат виконання кожної операції.

In [11]:
arr3 = np.array([12, 24, 36, 48, 60])
print(arr3 * 2) #множення на 2
print(arr3 + 10) #додавання 10
print(arr3 ** 2) #піднесення до квадрату
print(np.sqrt(arr3)) #корінь квадратний

[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]


3. Статистичні функції

Створіть Numpy-масив data зі значеннями [18, 27, 33, 41, 52, 68, 79]

Середнє значення
Мінімум
Максимум
Суму всіх елементів

In [16]:
arr4 = np.array([18, 27, 33, 41, 52, 68, 79])
print(np.mean(arr4)) # середнє
print(np.min(arr4)) # мінімум
print(np.max(arr4)) # максимум
print(np.sum(arr4)) # сума


45.42857142857143
18
79
318


 Індексація

Створіть Numpy-масив arr зі значеннями [15, 22, 35, 44, 58, 67].

Перший елемент
Останній елемент
Елементи з індексами 1 до 3
Елементи більші за 40

In [25]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[arr > 40])
print(arr[3:]) # variant 2 in case numbers are not mixed - sorted array

15
67
[22 35 44]
[44 58 67]
[44 58 67]


5. Двовимірні масиви
Задано матрицю 3x3.
Виконайте наступні дії з функціоналом Numpy
Виведіть форму (shape) матриці
Виведіть перший рядок
Виведіть другу колонку
Обчисліть суму всіх елементів
Обчисліть середнє всіх елементів

In [34]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])
print(matrix.shape) # matrix shape
print(matrix[0]) # 1 row
print(matrix[:, 1]) # 2 column
print(matrix.sum()) # sum of all elements
print(matrix.mean()) # mean of all elements

(3, 3)
[2 4 6]
[ 4 10 16]
90
10.0
